stages:
- stage: Docker
  displayName: Build & Push Docker image to AWS ECR
  jobs:
  - job: Build_and_Push
    displayName: Build & Push Docker image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        repository: '180729926970.dkr.ecr.eu-west-1.amazonaws.com/hello-world'

    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'awsCredentials'
        regionName: 'eu-west-1'
        imageSource: 'imagename'
        sourceImageName: '180729926970.dkr.ecr.eu-west-1.amazonaws.com/hello-world'
        sourceImageTag: $(Build.BuildId)
        pushTag: $(Build.BuildId)
        repositoryName: 'hello-world'
